[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
monitor_rts = 0
monitor_dtr = 0
build_src_filter = +<*> -<emit/> -<mqtt/>
lib_deps = crankyoldgit/IRremoteESP8266@^2.8.6

[env:esp32dev-emit]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
monitor_rts = 0
monitor_dtr = 0
build_src_filter = +<emit/> +<ir_emit.cpp> -<main.cpp> -<mqtt/>
lib_deps = crankyoldgit/IRremoteESP8266@^2.8.6
build_flags = -I include

[env:esp32dev-mqtt]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
monitor_rts = 0
monitor_dtr = 0
build_src_filter = +<mqtt/> +<ir_emit.cpp> +<emit/signals_data.cpp> -<emit/main.cpp> -<main.cpp>
lib_deps =
    crankyoldgit/IRremoteESP8266@^2.8.6
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.2.1
build_flags = -I include

; Captura IR:     pio run -e esp32dev -t upload
; Prueba emisor:  pio run -e esp32dev-emit -t upload
; WiFi + MQTT:    pio run -e esp32dev-mqtt -t upload
; Borrar flash:   pio run -t erase
